import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";

export const PRODUCT_IMAGES_BUCKET = "product-images";

const PRODUCT_IMAGE_OBJECT_PATH =
  /^(?:thumbnails\/)?products\/[a-z0-9][a-z0-9_-]{0,127}\/[a-f0-9]{64}\.webp$/i;

export type ProductImageStorageReference = {
  path?: string | null;
  thumbnailPath?: string | null;
  thumbnailUrl?: string | null;
  url?: string | null;
};

function normalizeProductImageObjectPath(value: string) {
  const normalized = value.trim().replace(/^\/+/, "");
  return PRODUCT_IMAGE_OBJECT_PATH.test(normalized) ? normalized : null;
}

/**
 * Accept only object paths generated by the product-image uploader in this
 * Supabase project. External URLs and legacy data URLs are deliberately never
 * treated as Storage objects to delete.
 */
export function getProductImageStorageObjectPath(value: string | null | undefined) {
  if (!value?.trim()) {
    return null;
  }

  const directPath = normalizeProductImageObjectPath(value);
  if (directPath) {
    return directPath;
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
  if (!supabaseUrl) {
    return null;
  }

  try {
    const projectUrl = new URL(supabaseUrl);
    const imageUrl = new URL(value);
    if (imageUrl.origin !== projectUrl.origin) {
      return null;
    }

    const basePath = projectUrl.pathname.replace(/\/$/, "");
    const publicPrefix = `${basePath}/storage/v1/object/public/${PRODUCT_IMAGES_BUCKET}/`;
    if (!imageUrl.pathname.startsWith(publicPrefix)) {
      return null;
    }

    return normalizeProductImageObjectPath(
      decodeURIComponent(imageUrl.pathname.slice(publicPrefix.length)),
    );
  } catch {
    return null;
  }
}

export function getProductImageStorageObjectPaths(
  references: ProductImageStorageReference[],
) {
  return Array.from(
    new Set(
      references.flatMap((reference) => {
        const values = [
          reference.path,
          reference.thumbnailPath,
          reference.url,
          reference.thumbnailUrl,
        ];

        return values.flatMap((value) => {
          const path = getProductImageStorageObjectPath(value);
          if (!path) {
            return [];
          }

          return path.startsWith("thumbnails/")
            ? [path, path.slice("thumbnails/".length)]
            : [path, `thumbnails/${path}`];
        });
      }),
    ),
  );
}

export async function deleteProductImageStorageObjects(
  client: SupabaseClient,
  references: ProductImageStorageReference[],
  keepReferences: ProductImageStorageReference[] = [],
) {
  const protectedPaths = new Set(
    getProductImageStorageObjectPaths(keepReferences),
  );
  const paths = getProductImageStorageObjectPaths(references).filter(
    (path) => !protectedPaths.has(path),
  );
  if (paths.length === 0) {
    return { error: null, paths };
  }

  const { error } = await client.storage.from(PRODUCT_IMAGES_BUCKET).remove(paths);
  return { error, paths };
}
